version: "3.5"
name: "productivity-app"
services:
  db:
    image: "postgres"
    restart: always
    container_name: productivity-app
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "productivity-app"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432

volumes:
  database-data: